export const ADD_ACADEMIC_WORK = `http://localhost:8080/plan/add-academic-work`;
export const EDIT_ACADEMIC_WORK = `http://localhost:8080/academic-work/update`;
export const DELETE_ACADEMIC_WORK = `http://localhost:8080/academic-work/delete`;
export const ADD_ACADEMIC_METHOD = `http://localhost:8080/plan/add-academic-methods`;
export const EDIT_ACADEMIC_METHOD = `http://localhost:8080/academic-method/update`;
export const DELETE_ACADEMIC_METHOD = `http://localhost:8080/academic-method/delete`;
export const ADD_EDUCATION_WORK = `http://localhost:8080/plan/add-educational-work`;
export const EDIT_EDUCATION_WORK = `http://localhost:8080/educational-work/update`;
export const DELETE_EDUCATION_WORK = `http://localhost:8080/educational-work/delete`;
export const ADD_SOCIAL_WORK = `http://localhost:8080/plan/add-social-work`;
export const EDIT_SOCIAL_WORK = `http://localhost:8080/social-work/update`;
export const DELETE_SOCIAL_WORK = `http://localhost:8080/social-work/delete`;
export const GET_LATEST_PLAN = `http://localhost:8080/plan/get-last-plan`;
export const GET_PLAN_BY_ID = (id: any) => `http://localhost:8080/plan/get-by-id?id=${id}`;